### ISSUE TITLE
Count-Down - complete

### ISSUE THREAD

**Issue by rschulzongithub** [rschulzongithub/permanent-efforts#2]
## Value statement
As a user
I need to meditate for a specific period of time
so that I am getting startet
## Description (Text, Scribble, Wireframe, Design)
A counter which counts down a specific time span.
The counter needs to get started when the user is ready.
## Acceptance criteria
- [ ] Counter counts down
- [ ] Counter starts when user wants to
- [ ] enjoable calm and dark Background
## Tasks
- [ ] Create counter component
- [ ] Create button component
- [ ] Styling background, counter & button component

## Size
medium
