### ISSUE TITLE
short user template

### ISSUE THREAD

**Issue by rschulzongithub** [rschulzongithub/permanent-efforts#3]
## Timer Settings
As I am getting more used to sit in silence
I need a flexible timer
so that I can sit for longer sessions
## Description (Text, Scribble, Wireframe, Design)
An option to change the timer period in an intuitiv and fast way.
## Acceptance criteria
- [ ] setting Options for minutes & seconds
- [ ] styling should match to the background

## Tasks
- [ ] find good looking icons for up & down settings
- [ ] linking icons to function timesetting
## Size
(medium)
