### ISSUE TITLE
Timer end-screen

### ISSUE THREAD

**Issue by rschulzongithub** [rschulzongithub/permanent-efforts#5]
## Timer end-screen
As I am meditating 
I need some kind of signal when session ends
so that I don't miss my other daily tasks
## Description (Text, Scribble, Wireframe, Design)
Some kind of smooth screen while timer is running. When timer runs out there should be signal like a 'gong' that should be smooth as well. There should be a new screen when timer runs out which says: 'You got it!' Or something like this instead of just seeing Zero.
## Acceptance criteria
- [ ] hearing the 'gong' when timer ends
- [ ] nice screen when timer is finished with a nice note
- [ ] smooth screen while timer is running
## Tasks
- [ ] find a good 'gong'
- [ ] how to: linking gong to timers-end
- [ ] building end screen
- [ ] how to: linking end screen to timers-end
## Size
large
