### ISSUE TITLE
Color decisions

### ISSUE THREAD

**Issue by rschulzongithub** [rschulzongithub/permanent-efforts#6]
## Color collection
As a cool metitation pioneer 
I need cool and smooth colors within my medi-app
so that I am feeling good while meditating
## Acceptance criteria
- [x] 3 different students have to say: I like!
## Tasks
- [x] searching for different color-collections
- [x] looking for different styles in other app's
## Size
(small, medium, large)
