### ISSUE TITLE
five awareness tasks

### ISSUE THREAD

**Issue by rschulzongithub** [rschulzongithub/permanent-efforts#7]
## Awareness Tasks
As a awareness-seeker
I need guidance
so that I am able to find it.
## Description (Text, Scribble, Wireframe, Design)
An exercise which comes randomly before the medi-sessions that one can read and then can meditate over.
## Acceptance criteria
- [ ] a random (out of 5) task card with written mind exercise that pops up before timer-start
## Tasks
- [ ] Preparing 5 exercises
- [ ] creating task box
- [ ] how to: box exercise choosen randomly when timer starts

## Size
large
